version: '3.8'

services:
  db:
    image: postgres:13.9-alpine
    volumes:
      - /var/lib/postgresql/data/
    env_file:
      - ./.env
    networks:
      - djangonetwork
  web:
    build: ../api_yamdb
    restart: always
    volumes:
    - static_value:/app/static/
    - media_value:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env
    networks:
      - djangonetwork
  nginx:
    image: nginx:1.23.3-alpine
    ports:
      - "5000:5000"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - web
    networks:
      - djangonetwork
networks:
  djangonetwork:
    driver: bridge
volumes:
  static_value:
  media_value: