# Generated by Django 2.2.16 on 2023-01-14 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0001_Add_Title_And_Category_And_Genre_Models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='genre',
            field=models.ManyToManyField(blank=True, related_name='titles', to='titles.Genre', verbose_name='Жанр'),
        ),
    ]
